plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '0.11.13-prototype'
group = 'com.eldritchartifice'

base {
    archivesName = 'eldritchartifice'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            mods {
                eldritchartifice {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            args '--nogui'
            mods {
                eldritchartifice {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven {
        url = 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'
    compileOnly fg.deobf('curse.maven:mana-and-artifice-406360:6847816')
    runtimeOnly fg.deobf('curse.maven:mana-and-artifice-406360:6847805')
    implementation fg.deobf('curse.maven:dimensionaldoors-284876:6421500')
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : 'eldritchartifice',
                'Specification-Vendor'    : 'Eldritch Artifice',
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : 'Eldritch Artifice'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
